### ISSUE TITLE
How did you get into programming/coding?

### ISSUE THREAD

**Issue by Duske** [zoepage/ama#1]
I'm interested in how did you get into programming/coding. Are you interested in programming from an early age? Did you study things like computer science?

**Comment by zoepage** [comment]
I got my first C64 when I was about 8. Because we moved from Poland to Germany shortly before that and I still had struggles with the language, I didn't had many friends, so I started to play around with code.

It always was a thing for me, but just on the side. I started to get into web development (when IE5.5 was cool) and realized, I could even make a living out of that... So I did and started my first job in an agency.

After several years of CSS, jQuery and PHP, I hit a wall (including my 3rd burnout), so I quit and studied CS. Had to drop out after 3 years, b/c of becoming a mom and had to earn an income. Gladly working in open source after that might have taught me more than I've learned in university.
