### ISSUE TITLE
what do you want to learn this year?

### ISSUE THREAD

**Issue by yoshuawuyts** [zoepage/ama#4]
Any skill you'd like to pick up? Anything you'd like to improve? Perhaps an interest you haven't pursued before?

**Comment by zoepage** [comment]
As I'm a single mom, I do not have much time to learn or play around with new things. This is why I am normally pretty late on adapting new things.

Right now, I have finally time to dive deeper into React / Flux / Redux. Feels great! Testing with Jasemine, because I just used Mocha / Chai / Tape until now. Definitely also want to take my studies on offline first further and write a complete new talk on that topic.

Last but not least, I really need to step up my drawing skills. My kiddo got so much better than me!

**Comment by yoshuawuyts** [comment]
That all sounds heaps good, thanks for answering! :D :sparkles:
