### ISSUE TITLE
Where do you see yourself in 5 years? 

### ISSUE THREAD

**Issue by mxstbr** [zoepage/ama#6]
I know how hard to answer that question is, but where do you see yourself in 5 years? What are some of the things you want to have done/achieved then? What's your "masterplan"? (if there is one)

**Comment by zoepage** [comment]
Actually I do not have one, because I do not believe in life plans. What you want might change all the time due to your circumstances and if you chaise that white rabbit without looking left / right... You'll never be truly happy. 

I just try to make the best out of things that come at me and like to empower others. Worked out for me really well, I guess. :)
